name = "opto_sync_gleam_web"
version = "0.1.0"
target = "javascript"

[dependencies]
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_stdlib = ">= 0.68.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
